spring:
  datasource:
    url: jdbc:sqlserver://srvdavidreyes.database.windows.net:1433;database=davidreyesDB;user=davidreyes@srvdavidreyes;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: davidreyes
    password: mesitas1A
  jpa:
     show-sql: true
     hibernate.ddl-auto: update
     properties:
      hibernate:
       dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191
